obj-$(CONFIG_BOARDDIAG) += cmd_boarddiag.o
obj-$(CONFIG_BOARDDIAG) += generateTestId.o
obj-$(CONFIG_BOARDDIAG) += eventlog.o
obj-$(CONFIG_BOARDDIAG) += consolelog.o
obj-$(CONFIG_BOARDDIAG) += process_diagtest_cmds.o

